# Edit the file path below to point to your combined_script_output.txt (generated by generate_text_for_automation.py)
# This file should contain multiple blocks of command lines per experiment
import subprocess

# Main function: reads the script file and executes command blocks in batches
def execute_script_blocks_in_batches(file_path, batch_size=2):
    try:
        # Read the content of the script file
        with open(file_path, 'r', encoding='utf-8') as file:
            lines = file.readlines()

        script_blocks = []
        current_block = []
        # Split the script into blocks, starting each when "cd cOMR" appears
        for line in lines:
            if line.strip().startswith("cd cOMR"):
                if current_block:
                    script_blocks.append(current_block)
                current_block = [line.strip()]
            elif line.strip(): # Skip empty lines
                current_block.append(line.strip())
        # Append the last block if it exists
        if current_block:
            script_blocks.append(current_block)

        total_blocks = len(script_blocks)
        # Process the script blocks in batches
        for i in range(0, total_blocks, batch_size):
            batch = script_blocks[i:i + batch_size]
            print(f"\nExecuting batch {i // batch_size + 1} with up to {batch_size} blocks:")

            # Combine all blocks in the batch into a single command string
            batch_commands = []
            # Combine each command block into a single string with '&' separator
            for block in batch:
                block_command = " & ".join(block)
                batch_commands.append(block_command)
            
            # Execute all commands in the batch in a single command prompt
            full_batch_command = " & ".join(batch_commands)
            print(f"\nExecuting combined batch command:\n{full_batch_command}")
            # Run the combined command in a new cmd window (Windows only)
            subprocess.run(f'start cmd /k "{full_batch_command}"', shell=True)

    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == "__main__":
  # Replace with the actual path to your script file
    script_file_path = "PATH\\TO\\combined_script_output.txt"
    execute_script_blocks_in_batches(script_file_path)
